namespace CCA_BE.Models
{
    public class AnualExcelModel
    {
        public int Id { get; set; }
        public string nameid { get; set; }
        public string fileName { get; set; }
        public bool state { get; set; }
        public int F3G3 { get; set; }
        public int K4K4 { get; set; }
        public int L4L4 { get; set; }
        public int M4M4 { get; set; }
        public string L8L10 { get; set; }
        public int L11L11 { get; set; }
        public int L12L12 { get; set; }
        public int L13L13 { get; set; }
        public int L14L14 { get; set; }
        public int L15L15 { get; set; }
        public int L16L16 { get; set; }
        public int L17L17 { get; set; }
        public int L18L18 { get; set; }
        public int L19L19 { get; set; }
        public int L20L20 { get; set; }
        public int L21L21 { get; set; }
        public int L22L22 { get; set; }
        public int L23L23 { get; set; }
        public int L24L24 { get; set; }
        public int L25L25 { get; set; }
        public int L26L26 { get; set; }
        public int L27L27 { get; set; }
        public int L28L28 { get; set; }
        public int L29L29 { get; set; }
        public int L30L30 { get; set; }
        public int L31L31 { get; set; }
        public int L32L32 { get; set; }
        public int L33L33 { get; set; }
        public int L34L34 { get; set; }
        public int L35L35 { get; set; }
        public int L36L36 { get; set; }
        public int L37L37 { get; set; }
        public int L38L38 { get; set; }
        public int L39L39 { get; set; }
        public int L40L40 { get; set; }
        public int L41L41 { get; set; }
        public int L42L42 { get; set; }
        public int L43L43 { get; set; }
        public int L44L44 { get; set; }
        public int L45L45 { get; set; }
        public int L47L47 { get; set; }
        public int L48L48 { get; set; }
        public int L49L49 { get; set; }
        public int L50L50 { get; set; }
        public int L51L51 { get; set; }
        public int L52L52 { get; set; }
        public int L53L53 { get; set; }
        public int L54L54 { get; set; }
        public int L55L55 { get; set; }
        public int L56L56 { get; set; }
        public int L57L57 { get; set; }
        public int L58L58 { get; set; }
        public int L59L59 { get; set; }
        public int L60L60 { get; set; }
        public int L64L64 { get; set; }
        public int L65L65 { get; set; }
        public int L66L66 { get; set; }
        public int L67L67 { get; set; }
        public int L68L68 { get; set; }
        public int L69L69 { get; set; }
        public int L70L70 { get; set; }
        public int L71L71 { get; set; }
        public int L72L72 { get; set; }
        public int L73L73 { get; set; }
        public int L74L74 { get; set; }
        public int L75L75 { get; set; }
        public int L76L76 { get; set; }
        public int L77L77 { get; set; }
        public int L78L78 { get; set; }
        public int L79L79 { get; set; }
        public int L80L80 { get; set; }
        public int L81L81 { get; set; }
        public int L82L82 { get; set; }
        public int L83L83 { get; set; }
        public int L84L84 { get; set; }
        public int L85L85 { get; set; }
        public int L86L86 { get; set; }
        public int L87L87 { get; set; }
        public int L88L88 { get; set; }
        public int L89L89 { get; set; }
        public int L90L90 { get; set; }
        public int L91L91 { get; set; }

    }
}